include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable some strict rules for easier development
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
